# Generated by Django 4.0.5 on 2022-06-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingredient_menu_plate_schedulemenu_publicmenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='personalized',
            field=models.BooleanField(default=False),
        ),
    ]
