# Generated by Django 4.0.5 on 2022-06-24 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_plate_personalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemenu',
            name='coyote',
        ),
        migrations.AddField(
            model_name='schedulemenu',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
