# Generated by Django 4.0.5 on 2022-06-25 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_schedulemenu_coyote_schedulemenu_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coyote',
        ),
    ]
